USE CentroMedico
GO
CREATE TYPE Paciente FROM INT NOT NULL;
GO
CREATE TYPE Medico FROM INT NOT NULL;
GO
CREATE TYPE Historia FROM INT NOT NULL;
GO
CREATE TYPE Pago FROM INT NOT NULL;
GO
CREATE TYPE Turno FROM INT NOT NULL;
GO
CREATE TYPE Concepto FROM TINYINT NOT NULL;
GO
CREATE TYPE Especialidad FROM INT NOT NULL;
GO
CREATE TYPE Observacion FROM VARCHAR(1000);
GO
CREATE TYPE Estado FROM SMALLINT NOT NULL;


