USE CentroMedico
GO


ALTER TABLE HistoriasPacientes
	ADD CONSTRAINT FK_HistP_Paciente FOREIGN KEY(idPaciente) REFERENCES Pacientes(idPaciente)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE HistoriasPacientes
	ADD CONSTRAINT FK_HistP_Medico FOREIGN KEY (idMedico) REFERENCES Medicos(idMedico)
	ON DELETE CASCADE ON UPDATE CASCADE	;
GO

ALTER TABLE HistoriasPacientes
	ADD CONSTRAINT FK_HistP_Historia FOREIGN KEY(idHistoria) REFERENCES Historias(idHistoria)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE Turnos
	ADD CONSTRAINT FK_Estado FOREIGN KEY (estado) REFERENCES TurnosEstados(IdEstado)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE TurnosPacientes
	ADD CONSTRAINT FK_TurnoP_Paciente FOREIGN KEY (idPaciente) REFERENCES Pacientes(idPaciente)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE TurnosPacientes
	ADD CONSTRAINT FK_TurnoP_Turno FOREIGN KEY(idTurno) REFERENCES Turnos(idTurno)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE TurnosPacientes
	ADD CONSTRAINT FK_TurnoP_Medico FOREIGN KEY(idMedico) REFERENCES Medicos(idMedico)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE PagosPacientes
	ADD CONSTRAINT FK_PagoP_Pago FOREIGN KEY(idPago) REFERENCES Pagos(idPago)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE PagosPacientes
	ADD CONSTRAINT FK_PagoP_Paciente FOREIGN KEY(idPaciente) REFERENCES Pacientes(idPaciente)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE PagosPacientes
	ADD CONSTRAINT FK_PagoP_Turno FOREIGN KEY(idTurno) REFERENCES Turnos(idTurno)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE MedicosEspecialidades
	ADD CONSTRAINT FK_MedicoEsp_Especialidad FOREIGN KEY(idEspecialidad) 
	    REFERENCES Especialidades(idEspecialidad)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE MedicosEspecialidades
	ADD CONSTRAINT FK_MedicoEsp_Medico FOREIGN KEY(idMedico) REFERENCES Medicos(idMedico)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE Pacientes
	ADD CONSTRAINT FK_Paciente_Pais FOREIGN KEY(idPais) REFERENCES Paises(idPais)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE Pacientes
	ADD CONSTRAINT FK_TipoIdPaciente FOREIGN KEY(tipoIdentif) REFERENCES tipos(idTipo)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE Pagos
	ADD CONSTRAINT FK_Pago_Concepto FOREIGN KEY(idConcepto) REFERENCES Conceptos(idConcepto)
	ON DELETE CASCADE ON UPDATE CASCADE 
GO

