USE CentroMedico
GO


ALTER TABLE HistoriaPaciente
	ADD CONSTRAINT FK_HistP_Paciente FOREIGN KEY(idPaciente) REFERENCES Paciente(idPaciente)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE HistoriaPaciente
	ADD CONSTRAINT FK_HistP_Medico FOREIGN KEY (idMedico) REFERENCES Medico(idMedico)
	ON DELETE CASCADE ON UPDATE CASCADE	;
GO

ALTER TABLE HistoriaPaciente
	ADD CONSTRAINT FK_HistP_Historia FOREIGN KEY(idHistoria) REFERENCES Turno(idHistoria)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE TurnoPaciente
	ADD CONSTRAINT FK_TurnoP_Paciente FOREIGN KEY (idPaciente) REFERENCES Paciente(idPaciente)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE TurnoPaciente
	ADD CONSTRAINT FK_TurnoP_Turno FOREIGN KEY(idTurno) REFERENCES Turno(idTurno)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE TurnoPaciente
	ADD CONSTRAINT FK_TurnoP_Medico FOREIGN KEY(idMedico) REFERENCES Medico(idMedico)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE PagoPaciente
	ADD CONSTRAINT FK_PagoP_Pago FOREIGN KEY(idPago) REFERENCES Pago(idPago)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE PagoPaciente
	ADD CONSTRAINT FK_PagoP_Paciente FOREIGN KEY(idPaciente) REFERENCES Paciente(idPaciente)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE PagoPaciente
	ADD CONSTRAINT FK_PagoP_Turno FOREIGN KEY(idTurno) REFERENCES Turno(idTurno)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE MedicoEspecialidad
	ADD CONSTRAINT FK_MedicoEsp_Especialidad FOREIGN KEY(idEspecialidad) REFERENCES Especialidad(idEspecialidad)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE MedicoEspecialidad
	ADD CONSTRAINT FK_MedicoEsp_Medico FOREIGN KEY(idMedico) REFERENCES Medico(idMedico)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE Paciente
	ADD CONSTRAINT FK_Paciente_Pais FOREIGN KEY(idPais) REFERENCES Pais(idPais)
	ON DELETE CASCADE ON UPDATE CASCADE
GO

ALTER TABLE Pago
	ADD CONSTRAINT FK_Pago_Concepto FOREIGN KEY(idConcepto) REFERENCES Concepto(idConcepto)
	ON DELETE CASCADE ON UPDATE CASCADE 
GO
