USE CentroMedico
GO
INSERT INTO Pais  VALUES ('AFG','Afganistán')
INSERT INTO Pais  VALUES ('ALB','Albania')
INSERT INTO Pais  VALUES ('DEU','Alemania')
INSERT INTO Pais  VALUES ('AND','Andorra')
INSERT INTO Pais  VALUES ('AGO','Angola')
INSERT INTO Pais  VALUES ('ATG','Antigua y Barbuda')
INSERT INTO Pais  VALUES ('SAU','Arabia Saudita')
INSERT INTO Pais  VALUES ('DZA','Argelia')
INSERT INTO Pais  VALUES ('ARG','Argentina')
INSERT INTO Pais  VALUES ('ARM','Armenia')
INSERT INTO Pais  VALUES ('AUS','Australia')
INSERT INTO Pais  VALUES ('AUT','Austria')
INSERT INTO Pais  VALUES ('AZE','Azerbaiyán')
INSERT INTO Pais  VALUES ('BHS','Bahamas')
INSERT INTO Pais  VALUES ('BHR','Bahrein')
INSERT INTO Pais  VALUES ('BGD','Bangladesh')
INSERT INTO Pais  VALUES ('BRB','Barbados')
INSERT INTO Pais  VALUES ('BLR','Belarús')
INSERT INTO Pais  VALUES ('BLZ','Belice')
INSERT INTO Pais  VALUES ('BEN','Benin')
INSERT INTO Pais  VALUES ('BTN','Bhután')
INSERT INTO Pais  VALUES ('BOL','Bolivia')
INSERT INTO Pais  VALUES ('BIH','Bosnia y Herzegovina')
INSERT INTO Pais  VALUES ('BWA','Botswana')
INSERT INTO Pais  VALUES ('BRA','Brasil')
INSERT INTO Pais  VALUES ('BRN','Brunei Darussalam')
INSERT INTO Pais  VALUES ('BGR','Bulgaria')
INSERT INTO Pais  VALUES ('BFA','Burkina Faso')
INSERT INTO Pais  VALUES ('BDI','Burundi')
INSERT INTO Pais  VALUES ('BEL','Bélgica')
INSERT INTO Pais  VALUES ('CPV','Cabo Verde')
INSERT INTO Pais  VALUES ('KHM','Camboya')
INSERT INTO Pais  VALUES ('CMR','Camerún')
INSERT INTO Pais  VALUES ('CAN','Canadá')
INSERT INTO Pais  VALUES ('TCD','Chad')
INSERT INTO Pais  VALUES ('CZE','Chequia')
INSERT INTO Pais  VALUES ('CHL','Chile')
INSERT INTO Pais  VALUES ('CHN','China')
INSERT INTO Pais  VALUES ('CYP','Chipre')
INSERT INTO Pais  VALUES ('COL','Colombia')
INSERT INTO Pais  VALUES ('COM','Comoras')
INSERT INTO Pais  VALUES ('COG','Congo')
INSERT INTO Pais  VALUES ('CRI','Costa Rica')
INSERT INTO Pais  VALUES ('HRV','Croacia')
INSERT INTO Pais  VALUES ('CUB','Cuba')
INSERT INTO Pais  VALUES ('CIV','Côte d''Ivoire')
INSERT INTO Pais  VALUES ('DNK','Dinamarca')
INSERT INTO Pais  VALUES ('DJI','Djibouti')
INSERT INTO Pais  VALUES ('DMA','Dominica')
INSERT INTO Pais  VALUES ('ECU','Ecuador')
INSERT INTO Pais  VALUES ('EGY','Egipto')
INSERT INTO Pais  VALUES ('SLV','El Salvador')
INSERT INTO Pais  VALUES ('ARE','Emiratos Árabes Unidos')
INSERT INTO Pais  VALUES ('ERI','Eritrea')
INSERT INTO Pais  VALUES ('SVK','Eslovaquia')
INSERT INTO Pais  VALUES ('SVN','Eslovenia')
INSERT INTO Pais  VALUES ('ESP','España')
INSERT INTO Pais  VALUES ('USA','Estados Unidos de América')
INSERT INTO Pais  VALUES ('EST','Estonia')
INSERT INTO Pais  VALUES ('SWZ','Eswatini')
INSERT INTO Pais  VALUES ('ETH','Etiopía')
INSERT INTO Pais  VALUES ('RUS','Federación de Rusia')
INSERT INTO Pais  VALUES ('FJI','Fiji')
INSERT INTO Pais  VALUES ('PHL','Filipinas')
INSERT INTO Pais  VALUES ('FIN','Finlandia')
INSERT INTO Pais  VALUES ('FRA','Francia')
INSERT INTO Pais  VALUES ('GAB','Gabón')
INSERT INTO Pais  VALUES ('GMB','Gambia')
INSERT INTO Pais  VALUES ('GEO','Georgia')
INSERT INTO Pais  VALUES ('GHA','Ghana')
INSERT INTO Pais  VALUES ('GRD','Granada')
INSERT INTO Pais  VALUES ('GRC','Grecia')
INSERT INTO Pais  VALUES ('GTM','Guatemala')
INSERT INTO Pais  VALUES ('GIN','Guinea')
INSERT INTO Pais  VALUES ('GNQ','Guinea Ecuatorial')
INSERT INTO Pais  VALUES ('GNB','Guinea-Bissau')
INSERT INTO Pais  VALUES ('GUY','Guyana')
INSERT INTO Pais  VALUES ('HTI','Haití')
INSERT INTO Pais  VALUES ('HND','Honduras')
INSERT INTO Pais  VALUES ('HUN','Hungría')
INSERT INTO Pais  VALUES ('IND','India')
INSERT INTO Pais  VALUES ('IDN','Indonesia')
INSERT INTO Pais  VALUES ('IRQ','Iraq')
INSERT INTO Pais  VALUES ('IRL','Irlanda')
INSERT INTO Pais  VALUES ('IRN','Irán (República Islámica del)')
INSERT INTO Pais  VALUES ('ISL','Islandia')
INSERT INTO Pais  VALUES ('COK','Islas Cook')
INSERT INTO Pais  VALUES ('FRO','Islas Feroe')
INSERT INTO Pais  VALUES ('MHL','Islas Marshall')
INSERT INTO Pais  VALUES ('SLB','Islas Salomón')
INSERT INTO Pais  VALUES ('ISR','Israel')
INSERT INTO Pais  VALUES ('ITA','Italia')
INSERT INTO Pais  VALUES ('JAM','Jamaica')
INSERT INTO Pais  VALUES ('JPN','Japón')
INSERT INTO Pais  VALUES ('JOR','Jordania')
INSERT INTO Pais  VALUES ('KAZ','Kazajstán')
INSERT INTO Pais  VALUES ('KEN','Kenya')
INSERT INTO Pais  VALUES ('KGZ','Kirguistán')
INSERT INTO Pais  VALUES ('KIR','Kiribati')
INSERT INTO Pais  VALUES ('KWT','Kuwait')
INSERT INTO Pais  VALUES ('LSO','Lesotho')
INSERT INTO Pais  VALUES ('LVA','Letonia')
INSERT INTO Pais  VALUES ('LBR','Liberia')
INSERT INTO Pais  VALUES ('LBY','Libia')
INSERT INTO Pais  VALUES ('LTU','Lituania')
INSERT INTO Pais  VALUES ('LUX','Luxemburgo')
INSERT INTO Pais  VALUES ('LBN','Líbano')
INSERT INTO Pais  VALUES ('MKD','Macedonia del Norte')
INSERT INTO Pais  VALUES ('MDG','Madagascar')
INSERT INTO Pais  VALUES ('MYS','Malasia')
INSERT INTO Pais  VALUES ('MWI','Malawi')
INSERT INTO Pais  VALUES ('MDV','Maldivas')
INSERT INTO Pais  VALUES ('MLT','Malta')
INSERT INTO Pais  VALUES ('MLI','Malí')
INSERT INTO Pais  VALUES ('MAR','Marruecos')
INSERT INTO Pais  VALUES ('MUS','Mauricio')
INSERT INTO Pais  VALUES ('MRT','Mauritania')
INSERT INTO Pais  VALUES ('FSM','Micronesia (Estados Federados de)')
INSERT INTO Pais  VALUES ('MNG','Mongolia')
INSERT INTO Pais  VALUES ('MNE','Montenegro')
INSERT INTO Pais  VALUES ('MOZ','Mozambique')
INSERT INTO Pais  VALUES ('MMR','Myanmar')
INSERT INTO Pais  VALUES ('MEX','México')
INSERT INTO Pais  VALUES ('MCO','Mónaco')
INSERT INTO Pais  VALUES ('NAM','Namibia')
INSERT INTO Pais  VALUES ('NRU','Nauru')
INSERT INTO Pais  VALUES ('NPL','Nepal')
INSERT INTO Pais  VALUES ('NIC','Nicaragua')
INSERT INTO Pais  VALUES ('NGA','Nigeria')
INSERT INTO Pais  VALUES ('NIU','Niue')
INSERT INTO Pais  VALUES ('NOR','Noruega')
INSERT INTO Pais  VALUES ('NZL','Nueva Zelandia')
INSERT INTO Pais  VALUES ('NER','Níger')
INSERT INTO Pais  VALUES ('OMN','Omán')
INSERT INTO Pais  VALUES ('PAK','Pakistán')
INSERT INTO Pais  VALUES ('PLW','Palau')
INSERT INTO Pais  VALUES ('PAN','Panamá')
INSERT INTO Pais  VALUES ('PNG','Papua Nueva Guinea')
INSERT INTO Pais  VALUES ('PRY','Paraguay')
INSERT INTO Pais  VALUES ('NLD','Países Bajos')
INSERT INTO Pais  VALUES ('PER','Perú')
INSERT INTO Pais  VALUES ('POL','Polonia')
INSERT INTO Pais  VALUES ('PRT','Portugal')
INSERT INTO Pais  VALUES ('QAT','Qatar')
INSERT INTO Pais  VALUES ('GBR','Reino Unido de Gran Bretaña e Irlanda del Norte')
INSERT INTO Pais  VALUES ('CAF','República Centroafricana')
INSERT INTO Pais  VALUES ('LAO','República Democrática Popular Lao')
INSERT INTO Pais  VALUES ('COD','República Democrática del Congo')
INSERT INTO Pais  VALUES ('DOM','República Dominicana')
INSERT INTO Pais  VALUES ('PRK','República Popular Democrática de Corea')
INSERT INTO Pais  VALUES ('TZA','República Unida de Tanzanía')
INSERT INTO Pais  VALUES ('KOR','República de Corea')
INSERT INTO Pais  VALUES ('MDA','República de Moldova')
INSERT INTO Pais  VALUES ('SYR','República Árabe Siria')
INSERT INTO Pais  VALUES ('ROU','Rumania')
INSERT INTO Pais  VALUES ('RWA','Rwanda')
INSERT INTO Pais  VALUES ('KNA','Saint Kitts y Nevis')
INSERT INTO Pais  VALUES ('WSM','Samoa')
INSERT INTO Pais  VALUES ('SMR','San Marino')
INSERT INTO Pais  VALUES ('VCT','San Vicente y las Granadinas')
INSERT INTO Pais  VALUES ('LCA','Santa Lucía')
INSERT INTO Pais  VALUES ('STP','Santo Tomé y Príncipe')
INSERT INTO Pais  VALUES ('SEN','Senegal')
INSERT INTO Pais  VALUES ('SRB','Serbia')
INSERT INTO Pais  VALUES ('SYC','Seychelles')
INSERT INTO Pais  VALUES ('SLE','Sierra Leona')
INSERT INTO Pais  VALUES ('SGP','Singapur')
INSERT INTO Pais  VALUES ('SOM','Somalia')
INSERT INTO Pais  VALUES ('LKA','Sri Lanka')
INSERT INTO Pais  VALUES ('ZAF','Sudáfrica')
INSERT INTO Pais  VALUES ('SDN','Sudán')
INSERT INTO Pais  VALUES ('SSD','Sudán del Sur')
INSERT INTO Pais  VALUES ('SWE','Suecia')
INSERT INTO Pais  VALUES ('CHE','Suiza')
INSERT INTO Pais  VALUES ('SUR','Suriname')
INSERT INTO Pais  VALUES ('THA','Tailandia')
INSERT INTO Pais  VALUES ('TJK','Tayikistán')
INSERT INTO Pais  VALUES ('TLS','Timor-Leste')
INSERT INTO Pais  VALUES ('TGO','Togo')
INSERT INTO Pais  VALUES ('TKL','Tokelau')
INSERT INTO Pais  VALUES ('TON','Tonga')
INSERT INTO Pais  VALUES ('TTO','Trinidad y Tabago')
INSERT INTO Pais  VALUES ('TKM','Turkmenistán')
INSERT INTO Pais  VALUES ('TUR','Turquía')
INSERT INTO Pais  VALUES ('TUV','Tuvalu')
INSERT INTO Pais  VALUES ('TUN','Túnez')
INSERT INTO Pais  VALUES ('UKR','Ucrania')
INSERT INTO Pais  VALUES ('UGA','Uganda')
INSERT INTO Pais  VALUES ('URY','Uruguay')
INSERT INTO Pais  VALUES ('UZB','Uzbekistán')
INSERT INTO Pais  VALUES ('VUT','Vanuatu')
INSERT INTO Pais  VALUES ('VEN','Venezuela')
INSERT INTO Pais  VALUES ('VNM','Viet Nam')
INSERT INTO Pais  VALUES ('YEM','Yemen')
INSERT INTO Pais  VALUES ('ZMB','Zambia');
INSERT INTO Pais  VALUES ('ZWE','Zimbabwe')
